name: CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.14.0

      - name: Cache node modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --immutable
        if: steps.node-modules-cache.outputs.cache-hit != 'true'

      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test --ci --runInBand

      - name: Test Summary
        if: always()
        uses: test-summary/action@v1
        with:
          paths: "test-reports/junit.xml"

      - name: Detailed test report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Test Report
          path: test-reports/report.html
